spring:
  application:
    name: status
  datasource:
    url: ${RDB_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${RDB_USER:sa}
    password: ${RDB_PASSWORD:}
    driver-class-name: ${RDB_DRIVER_CLASS:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${RDB_DDL:create-drop}
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: true

logging:
  config: classpath:log4j.xml

springdoc:
  swagger-ui:
    path: '/docs'

management:
  endpoints:
    web:
      base-path: /prom
      exposure:
        include: prometheus