# .github/workflows/jira-issue-sync.yml

name: Create Jira Issue on GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      # 1. Jira 로그인 액션을 먼저 실행합니다.
      # 여기서 GitHub Secrets를 사용하여 인증합니다.
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      # 2. Jira 이슈 생성 액션을 실행합니다.
      # 로그인 정보는 이전 스텝에서 처리했으므로 여기서는 제거합니다.
      - name: Create Jira Issue
        uses: atlassian/gajira-create@v3
        with:
          project: 'NVS'
          issuetype: 'Task'
          summary: '[GitHub Issue] ${{ github.event.issue.title }}'
          description: |
            ${{ github.event.issue.body }}

            ---
            *Created from GitHub Issue:* ${{ github.event.issue.html_url }}